workflows:
  react-native-ios:
    name: Build iOS App
    environment:
      vars:
        XCODE_WORKSPACE: "ios/XimiApp.xcworkspace"
        XCODE_SCHEME: "XimiApp"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          yarn install
          cd ios && pod install
      - name: Build iOS
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/XimiApp.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/XimiApp.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/export
    artifacts:
      - build/**/Build/**/*.app
      - $CM_BUILD_DIR/export/*.ipa
    publishing:
      email:
        recipients:
          - duy2172003@gmail.com
